# Generated by Django 2.1.7 on 2019-02-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schapp', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('patron', models.CharField(max_length=30)),
                ('desc', models.TextField()),
            ],
        ),
    ]
