# Generated by Django 2.1.7 on 2019-02-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schapp', '0005_anthem_mission_motto_vision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anthem',
            old_name='content',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='content',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='motto',
            old_name='content',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='vision',
            old_name='content',
            new_name='desc',
        ),
    ]
