# Generated by Django 2.1.7 on 2019-03-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schapp', '0009_coach_message_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='desc',
            field=models.TextField(default=1),
        ),
    ]
